Open polygon fix for Issue #23
BrunoFenzl/svg-round-corners pull request #24
Opened 2021-04-13 17:37 UTC by mikest

In this PR:
- Update for fixing #23, open polygons will no longer add arcs to beginning/end of lines.
- Added `.prettierrc` to match existing .editorconfig and updated all files to match formatting spec. (lots of quote updates.)
- Updated `package.json` a few dependencies which had security issues, some still remain as they're breaking changes.
- Update `.gitignore` to exclude .DS_Store :smile:
- Add evt.metaKey for toggling open/closed behavior in demo.

2021-04-13 17:38 UTC, mikest commented
Apologies for not splitting out the formatting from the code fix. If it's super irritating I can remove those and resubmit.

2021-04-13 20:14 UTC, BrunoFenzl commented
Thanks for working on this @mikest! I skimmed through your changes and everything looks good! I'll pull your changes, do 
 some tests and get back to you. Thank you again.

2021-04-15 07:16 UTC, BrunoFenzl requested changes
Thank you for working on this! Everything works as expected. Please, just take a look in my comment.

2021-04-15 07:16 UTC, BrunoFenzl commented on demo/main.js
> +    this.updatePath(evt.metaKey);
Works great! Please, just add a short note in the controls box that click + (cmd/windows) keys closes the path.

2021-04-15 18:50 UTC, mikest commented on demo/main.js
> +    this.updatePath(evt.metaKey);
will do!

2021-04-15 19:49 UTC, BrunoFenzl approved these changes
Great! Everything looks good. I'll merge it. Thanks again for working on this :)

2021-04-15 19:50 UTC, merged